name: deploy

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    Deployando:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./Parcial2/clase19/otro-proyecto/
        steps:
            - name: Descargar codigo
              uses: actions/checkout@v4
            - name: Descargar nodeJS
              uses: actions/setup-node@v4
            - name: Confirmar nodeJS
              run: node -v
            - name: Confirmo npm
              run: npm -v
            - name: Descargar librerias
              run: npm ci
            - name: Verificamos donde estamos
              run: ls -la
            - name: Hacer build del proyecto
              run: npx vite build
            - name: Guardamos el dist
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./Parcial2/clase19/otro-proyecto/dist
            - name: Configuramos GH Pages
              uses: actions/configure-pages@v5
            - name: Publicamos la página (ahorasi)
              uses: actions/deploy-pages@v4
