name: Hola Gente

on:
  push:
  workflow_dispatch:

jobs:
  buenas:
    runs-on: ubuntu-latest

    steps:
      - name: saludo
        run: echo "Como va todo muchachosss"
      - name: descargo mi codigo
        uses: actions/checkout@v4
      - name: checo donde estoy
        run: pwd
      - name: checo que archivos hay aca
        run: ls -la
      - name: dame un poco de ese nodejs
        uses: actions/setup-node@v4
      - name: confirmo si me dieron un poco de ese nodejs
        run: node -v
      - name: confirmo si también me dieron un poco de npm
        run: npm -v
      - name: me saco unas cuantas librerias
        run: npm ci
      - name: checo si el código funciona (no lo hace pq tengo funciones sin usar)
        run: npm run check-js
