name: Hola Gente

on:
  push:
  workflow_dispatch:

jobs:
  buenas:
    runs-on: ubuntu-latest

    steps:
      - name: saluditos
        run: echo "Como va todo muchachosss"
      - name: lee mi codigo
        uses: actions/checkout@v4