name: Hola Gente

on:
  push:
  workflow_dispatch:

jobs:
  buenas:
    runs-on: ubuntu-latest

    steps:
      - name: saludo
        run: echo "Como va todo muchachosss"
      - name: descargo mi codigo
        uses: actions/checkout@v4
      - name: checo donde estoy
        run: pwd
      - name: checo que archivos hay aca
        run: ls -la
      - name: dame un poco de ese nodejs
        uses: actions/setup-node@v4
